## Numpy and Pandas

In [42]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
a.std()

1.4142135623730951

In [4]:
b = a.sum()

In [5]:
b

15

In [6]:
b += 5

In [7]:
print(b.sum())

20


In [8]:
b

20

In [10]:
a[3:]

array([4, 5])

In [11]:
a.cumsum()

array([ 1,  3,  6, 10, 15])

In [20]:
np.sqrt(b)

4.47213595499958

In [21]:
data = ("사과", "배", "포도", "토마토", "딸기")

In [22]:
print(data)

('\xec\x82\xac\xea\xb3\xbc', '\xeb\xb0\xb0', '\xed\x8f\xac\xeb\x8f\x84', '\xed\x86\xa0\xeb\xa7\x88\xed\x86\xa0', '\xeb\x94\xb8\xea\xb8\xb0')


In [23]:
print(type(data))

<type 'tuple'>


In [25]:
print(data.count(100))

0


In [26]:
print(data[2:4])

('\xed\x8f\xac\xeb\x8f\x84', '\xed\x86\xa0\xeb\xa7\x88\xed\x86\xa0')


In [27]:
print(data*2)

('\xec\x82\xac\xea\xb3\xbc', '\xeb\xb0\xb0', '\xed\x8f\xac\xeb\x8f\x84', '\xed\x86\xa0\xeb\xa7\x88\xed\x86\xa0', '\xeb\x94\xb8\xea\xb8\xb0', '\xec\x82\xac\xea\xb3\xbc', '\xeb\xb0\xb0', '\xed\x8f\xac\xeb\x8f\x84', '\xed\x86\xa0\xeb\xa7\x88\xed\x86\xa0', '\xeb\x94\xb8\xea\xb8\xb0')


In [29]:
data = {100, 200, 300}
print(type(data))

<type 'set'>


In [30]:
data.add(700)

In [31]:
data

{100, 200, 300, 700}

In [35]:
data.update([1200, 3100])

In [38]:
data
data.remove(100)

In [39]:
data.clear()
data

set()

In [40]:
A = {100, 200, 300, 400, 500}
B = {100, 140, 200, 250, 300}

In [46]:
print(A.symmetric_difference(B))

set([400, 500, 250, 140])


In [47]:
data = {"사과":300, "배":200, "포도":500, "딸기":700}
print(type(data))

<type 'dict'>


In [48]:
print(data["사과"])

300


In [49]:
print(data.get("사과"))

300


In [50]:
data["메론"] = 100

In [51]:
data

{'\xeb\x94\xb8\xea\xb8\xb0': 700,
 '\xeb\xa9\x94\xeb\xa1\xa0': 100,
 '\xeb\xb0\xb0': 200,
 '\xec\x82\xac\xea\xb3\xbc': 300,
 '\xed\x8f\xac\xeb\x8f\x84': 500}

In [55]:
print(sorted(data.values()))

[100, 200, 300, 500, 700]


In [56]:
a = 100
if a==100:
    print("crt")
else:
    print("n")

crt


In [58]:
while a==100:
    print(a)
    a+=1;

100


In [59]:
a = 1
while a<=5:
    print(a)
    a+=1

1
2
3
4
5


In [61]:
num_list = [1,2,3,4,5]
for num in num_list:
    print(num)

1
2
3
4
5


In [62]:
def f(x):
    return x+10
f(10)

20

In [63]:
print((lambda x: x+10)(10))

20


In [67]:
np = [1, 2, 3, 4, 5]
mp = [np, np, np]
mp

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

In [70]:
import numpy as np
a = np.array([1, 2, 4, 5, 7])
a[3:]

array([5, 7])

In [71]:
b = a.sum()
b

19

In [73]:
np.sqrt(b)

4.358898943540674

In [74]:
a.std()

2.1354156504062622

In [75]:
a.cumsum()

array([ 1,  3,  7, 12, 19])

In [78]:
a = np.array([1, 2, 4, 5, 7])
b = np.array([a, a**2])
b
print(b.sum(axis = 0))
print(b.sum(axis = 1))

[ 2  6 20 30 56]
[19 95]


In [81]:
import pandas as pd

In [82]:
pandas_series = pd.Series([3000, 3200, 2700],
                         index = ['1', '2', '3'])
print(type(pandas_series))

<class 'pandas.core.series.Series'>


In [83]:
pandas_series

1    3000
2    3200
3    2700
dtype: int64

In [84]:
pandas_series[1:]

2    3200
3    2700
dtype: int64

In [98]:
import pandas as pd
df = pd.DataFrame([100, 200, 300, 400, 500], columns = [4], index = ['a', 'b', 'c', 'd', 'e'])
df

4
a  100
b  200
c  300
d  400
e  500

In [100]:
df.index

Index([u'a', u'b', u'c', u'd', u'e'], dtype='object')

In [101]:
df.columns

Int64Index([4], dtype='int64')

In [103]:
df.ix['a']

C:\ProgramData\Anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':


4    100
Name: a, dtype: int64